[settings]
experimental = true
lockfile = true

[tools]
go = "1.22"
pulumi = "latest"
python = "3.12"
node = "20"

[env]
ANSIBLE_CONFIG = "ansible/ansible.cfg"
PULUMI_SKIP_UPDATE_CHECK = "true"
MOLECULE_NO_LOG = "false"
PY_COLORS = "1"
ANSIBLE_FORCE_COLOR = "1"
_.path = ["./bin"]
