[tools]
go = "1.22"
pulumi = "latest"
python = "3.12"
node = "20"

[env]
ANSIBLE_CONFIG = "ansible/ansible.cfg"
ANSIBLE_ROLES_PATH = "ansible/roles"
PULUMI_SKIP_UPDATE_CHECK = "true"
MOLECULE_NO_LOG = "false"
PY_COLORS = "1"
ANSIBLE_FORCE_COLOR = "1"

[settings]
experimental = true
