---
- name: Daemon reload
  ansible.builtin.systemd:
    daemon_reload: true

- name: Reload caddy
  ansible.builtin.systemd:
    name: caddy
    state: reloaded

- name: Restart caddy
  ansible.builtin.systemd:
    name: caddy
    state: restarted
