---
all:
  children:
    antarctica:
      hosts:
        antarctica-server:
          ansible_host: "{{ lookup('env', 'ANTARCTICA_HOST') | default('172.22.202.50', true) }}"
          ansible_port: 22
          ansible_user: antarctica
          ansible_ssh_private_key_file: "{{ lookup('env', 'ANTARCTICA_SSH_KEY') | default('', true) }}"
