---
all:
  children:
    antarctica:
      hosts:
        antarctica-server:
          ansible_host: "{{ lookup('env', 'ANTARCTICA_HOST') | default('antarctica.dev.nerds.run', true) }}"
          ansible_port: 22
          ansible_user: deploy
