---
- name: Daemon reload woodpecker
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart woodpecker-server
  ansible.builtin.systemd:
    name: woodpecker-server
    state: restarted

- name: Restart woodpecker-agent
  ansible.builtin.systemd:
    name: woodpecker-agent
    state: restarted
