---
- name: Antarctica Docker Registry deployment
  hosts: antarctica
  become: true

  roles:
    - role: container_runtime
      tags: [container_runtime]
    - role: docker_registry
      tags: [docker_registry]
    - role: caddy
      tags: [caddy]
