---
- name: Daemon reload forgejo
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart forgejo
  ansible.builtin.systemd:
    name: forgejo
    state: restarted

- name: Restart actions-runner
  ansible.builtin.systemd:
    name: actions-runner
    state: restarted
