---
galaxy_info:
  role_name: openvscode
  author: nerdsrun
  description: "OpenVSCode Server as Podman Quadlet container"
  license: BSD-3-Clause
  min_ansible_version: "2.17"
  platforms:
    - name: Debian
      versions:
        - bookworm
  galaxy_tags:
    - vscode
    - ide
    - podman
    - quadlet
dependencies:
  - role: container_runtime
