---
galaxy_info:
  role_name: forgejo
  author: nerdsrun
  description: "Forgejo git forge as Podman Quadlet container"
  license: BSD-3-Clause
  min_ansible_version: "2.17"
  platforms:
    - name: Debian
      versions:
        - bookworm
  galaxy_tags:
    - forgejo
    - gitea
    - git
    - podman
    - quadlet
dependencies:
  - role: container_runtime
  - role: postgresql
